SET(ShaderFiles
#spotlight.func
infinity.frag
geometry.frag
glyphs.frag
coordinates.frag
coordinates-tensor.frag
dtidepth.prog
dtidepth.vert
dtidepth.frag
dtilight.prog
dtilight.vert
dtilight.frag
vecvol.prog
vecvol.frag
vecvol.vert
lighting.frag
seeding.frag
matrix.frag
tensorglyph.prog
tensorglyph.frag
tensorglyph.vert
superquadric.frag
SHglyph.prog
SHglyph.vert
SHglyph.frag
CHglyph.prog
CHglyph.vert
CHglyph.frag
SphericalHarmonics.frag
trigonometry.frag
CylindricalHarmonics.frag
)
