/*
 * HARDIMeasuresPlugin.h
 *
 * 2011-04-29	Evert van Aart
 * - Version 1.0.0.
 * - First version.
 *
 * 2011-05-04	Evert van Aart
 * - Version 1.0.1.
 * - Added the volume measure.
 *
 * 2011-05-13	Evert van Aart
 * - Version 1.0.2.
 * - Improved attribute handling.
 *
 */


#ifndef bmia_HARDIMeasures_HARDIMeasuresPlugin_h
#define bmia_HARDIMeasures_HARDIMeasuresPlugin_h


/** Includes - Main Header */

#include "DTITool.h"

/** Includes - Qt */

#include <QDebug>
#include <QList>

/** Includes - VTK */

#include <vtkExecutive.h>
#include <vtkMatrix4x4.h>
#include <vtkImageData.h>
#include <vtkPointData.h>
#include <vtkDataArray.h>
#include <vtkAlgorithm.h>
#include <vtkDoubleArray.h>
#include <vtkIntArray.h>
#include <vtkObject.h>

/** Includes - Custom Files */

#include "HARDI/SphereTriangulator.h"
#include "vtkDiscreteSphereToScalarVolumeFilter.h"


namespace bmia {


/** This plugin converts a volume containing HARDI data to one or more scalar
	measure volumes, which can then be visualized using for example the Planes
	Visualization plugin. All output volumes are computed by request, meaning
	that the output volume will be empty until data is requested. Thus, plugins
	using data sets generated by this plugin should use the "Update" function
	on the "vtkImageData" object before using it.
*/

class HARDIMeasuresPlugin :	public plugin::Plugin, 
							public data::Consumer
{
	Q_OBJECT
	Q_INTERFACES(bmia::plugin::Plugin)
	Q_INTERFACES(bmia::data::Consumer)

	public:

		/** Return the current version of the plugin. */

		QString getPluginVersion()
		{
			return "1.0.2";
		}

		/** Constructor */

		HARDIMeasuresPlugin();

		/** Destructor */

		~HARDIMeasuresPlugin();

		/** The data manager calls this function whenever a new 
			data set is added to the manager. 
			@param ds	New data set. */

		virtual void dataSetAdded(data::DataSet * ds);
    
		/** The data manager calls this function whenever an existing
			data set is modified in some way. 
			@param ds	Modified data set. */

		virtual void dataSetChanged(data::DataSet * ds);

		/** The data manager calls this function whenever an existing
			data set is removed. */

		virtual void dataSetRemoved(data::DataSet * ds);

	protected:

	
	private:

		/** Structure to keep track of all outputs for a specific input image. */

		struct OutputInformation
		{
			data::DataSet * input;
			QList<data::DataSet *> outputs;
		};

		/** List of all input images that have been handled by this plugin. */

		QList<OutputInformation> images;

		/** List of all filters used to compute scalar measures for discrete sphere function volumes. */

		QList<vtkAlgorithm *> discreteSphereFilters;

		/** Find an input image in the list of images, and return its index. If
			the specified data set is not in the list of input images, -1 is returned.
			@param ds		Input data set. */

		int findInputImage(data::DataSet * ds);

		/** Find the indices of an output data set. If the specified data set
			has been generated by this plugin, true is returned, and the indices
			of the image (within the "images" list, and within the "outputs" list
			of the corresponding "OutputInformation" object) are set. If the
			target pointer is not stored in any list, false is returned, and
			the indices remain unchanged.
			@param ds		Output data set.
			@param imageID	Index of the "OutputInformation" object containing "ds".
			@param outID	Index of "ds" within the "outputs" list. */

		bool findOutputImage(data::DataSet * ds, int & imageID, int & outID);

}; // class HARDIMeasuresPlugin


} // namespace bmia


#endif // bmia_HARDIMeasures_HARDIMeasuresPlugin_h
